### ISSUE TITLE
List of Challenges

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#17]
## User Story
As a user
I want a list of challenges
so that I can choose one of them.

## Description
![image](https://user-images.githubusercontent.com/104211944/176657394-a0724511-1846-4b6a-b134-6cdae6c95fb3.png)

## Acceptance Criteria
- [x] there is more than one challenge at the challenges page

## Tasks
- [x] create a new branch
- [x] map over the challengeData array and pass the data to the challenge component

## Complexity
S

## Depends on
#18
