### ISSUE TITLE
Challenge

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#18]
## User Story
As a user
I want to have a sporting challenge
so that I have a goal that I can work towards.

## Description
![image](https://user-images.githubusercontent.com/104211944/176651359-09e29e95-04ca-4490-a32d-377c48f1f936.png)

## Acceptance Criteria
- [x] the challenge should have a picture, title and distance in km
- [x] it should have a start button
- [x] clicking on the start button, navigates the user to the active challenge page
- [x] the challenge should be listed on the challenges page

## Tasks
- [x] create a new branch
- [x] create a new component Challenge
- [x]  add an image, title and distance to the Challenge
- [x] add a start button as a navLink
- [x] clicking the button, navigate to the active challenge page
- [x] create challenges page and add the component to it

# Complexity
S / M

**Comment by JessicaLoers** [comment]
**Well done** 👍
