### ISSUE TITLE
Finishing Message

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#25]
## User Story
As a user
I want to be alerted when I finished my challenge,
so that I have a sense of achievement.

## Description
![image](https://user-images.githubusercontent.com/104211944/177634107-7095f649-9258-4518-984f-dff2ec95dc59.png)

## Acceptance Criteria
- [x] by finishing the challenge, a text will be displayed in place of the 'add activity' button
- [x] no further activities can be added

## Tasks
- [x] create new branch
- [x] don't show the button, when the total distance of all activities equals or exceeds the challenge goal

## Complexity
S
