### ISSUE TITLE
Message When Changing The Challenge

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#26]
## User Story
As a user
I want to be alerted when I change my active challenge,
so that I can still change my mind.

## Description
![image](https://user-images.githubusercontent.com/104211944/177521904-deb09ebe-d270-4903-b995-d54c865e3afc.png)

## Acceptance Criteria
- [x] when starting a new challenge, while another is still active, ask to confirm
- [ ] the new challenge will only be started when the user clicks on ok
- [ ] the previously active challenge will be paused

## Tasks
- [x] create new branch
- [x] add modal to challenge list page
- [x] clicking on start button opens the modal
- [x] ok button sets the status of the active challenge to paused and the new challenge to active

# Complexity
S
