### ISSUE TITLE
Sort Challenge List

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#29]
## User Story
As a user
I want to sort the challenges by their properties,
so that I can find a new fitting challenge faster.

## Description
![image](https://user-images.githubusercontent.com/104211944/177558106-6739cb60-1450-4a77-9fc1-a9d2cf8d54d5.png)
![image](https://user-images.githubusercontent.com/104211944/177559941-da2ccb85-1671-4e6a-87d1-c62aa827f245.png)

## Acceptance Criteria
- [x] there should be a field for sorting
- [x] you can chose between none, km ascending and km descending
- [x] the challenge list should be sorted according to the selected sort order

## Tasks
- [x] create a new branch
- [x] add a selection
- [x] by change -> sort the challenge list by the selection

## Complexity
M
