### ISSUE TITLE
Graphic For The Statistic

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#30]
## User Story
As a user
I want to see the progress of the challenge represented graphically,
so that I stay motivated.

## Description
![image](https://user-images.githubusercontent.com/104211944/177562618-d284c6d2-bd1c-44a8-8b0d-318904b9c6d7.png)

## Acceptance Criteria
- [x] the progress block has a doughnut with the distance to go and the finished distance
- [x] the percent should be in the doughnut middle
- [x] the total duration is still shown

## Tasks
- [x] create new branch
- [x] install charts.js
- [x] import Doughnut
- [x] prepare data
- [x] place the rest of the statistics data

## Complexity
M

**Comment by p-enz** [comment]
Looking very good. We will use charts.js aswell maybe we can share some ideas and tricks later on 😃  maybe something to checkout aswell https://react-chartjs-2.js.org/examples/doughnut-chart
