### ISSUE TITLE
Design For The Activities

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#38]
## User Story
As a designer
I want the activities to follow the design concept
so that the user can record his values more quickly.

## Description / Design Inspiration
<img width="1440" alt="Bildschirmfoto 2022-07-13 um 14 47 02" src="https://user-images.githubusercontent.com/104211944/178931374-113693a8-c79e-4509-be98-41e5acaaa237.png">

## Acceptance Criteria
- [x] the activities should be a unit
- [x] should distinguish itself from the background
- [x] should be based on the design

## Tasks
- [x]  create a new branch
- [x] create global variables for font and color, if not already available
- [x] apply the global variables to the activities
- [x] add box-shadow if necessary
