### ISSUE TITLE
NavBar Design

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#41]
## User Story
As a designer
I want the navigation to follow the design concept
so that the user knows which page he is on.

## Description / Design Inspiration
<img width="1440" alt="Bildschirmfoto 2022-07-13 um 14 47 02" src="https://user-images.githubusercontent.com/104211944/178931374-113693a8-c79e-4509-be98-41e5acaaa237.png">

## Acceptance Criteria
- [x] the navigation should be a unit
- [x] should distinguish itself from the background
- [x] should be based on the design
- [x] should highlight the active page

## Tasks
- [x]  create a new branch
- [x] create global variables for font and color, if not already available
- [x] apply the global variables to the navigation
- [x] add box-shadow if necessary
- [x] add different design to active icon
