### ISSUE TITLE
## User Story

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#51]
As a developer
I want to have my sortBar component tested so that bugs are avoided.

## Acceptance Criteria
- [ ] the component and the searchAndSort functions are tested
- [ ] tests runs successfully

## Tasks
- [ ] create a new branch
- [ ] add jest test to the header component
