### ISSUE TITLE
Modal Testing

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#52]
## user story
As a developer
I want to have the Modal component tested 
so that bugs are avoided.

## Acceptance Criteria
 - [x] the Modal and the ModalBackdrop are tested
 - [x] tests runs successfully

## Tasks
 - [x] create a new branch
 - [x] add jest tests to the Modal component
 - [x] add test to the ModalBackdrop
