### ISSUE TITLE
## user story

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#53]
As a developer
I want to have the NavBar component tested 
so that bugs are avoided.

## Acceptance Criteria
 - [ ] the NavBar is tested
 - [ ] tests runs successfully

## Tasks
 - [ ] create a new branch
 - [ ] add jest tests to the NavBar component
