### ISSUE TITLE
chronologically ordered date

### ISSUE THREAD

**Issue by UlrikeWerner** [UlrikeWerner/capstone-project#8]
## User Story
As a user
I want my activities to be sorted chronologically
so that I can find them easier.

## Description
![image](https://user-images.githubusercontent.com/104211944/174776776-a5734772-0c1b-4ab4-8a0c-7a88a2371ce5.png)

## Acceptance Criteria
- [x] the dates in the activity list are sorted from most recent to oldest

## Tasks
- [x] create a new branch
- [x] sort activities by date
- [x] map over sorted activities

## Complexity
xs

## depending on
#3
